### ISSUE TITLE
Cuando estara listo?

### ISSUE THREAD

**Issue by DvdQzd** [LucasNMachado/pf-backend#1]
Hola Lucas como estas? solo pasaba a preguntar cuando podria revisar esto, que sigue incompleto jajaj

(Eres el ultimo que me falta revisar)

**Comment by LucasNMachado** [comment]
Hola Profe! Recién lo veo, venía revisando la plataforma de coder.  Disculpe la demora. Estoy terminando con las rutas, espero terminarlo mañana. Si usted tiene que corregir lo voy a saber entender.
